### ISSUE TITLE
Add buildTypes for debug / release differentiation

### ISSUE THREAD

**Issue by bbbenja** [code-troopers/material-android-bootstrap#8]
Like we have on all projects, it could be interesting to directly have buildtypes configured for debug / release differentiation :

* set a different icon on debug (by adding a trooper for example)
* suffix versionName with .debug
* suffix applicationId with .debug

If you have other ideas don't hesitate.

Next steps could be to add gradle plugins to release / deploy but it is another subject.

Please vote with :+1:  or :-1: since github don't have the voting feature.

**Comment by mattboll** [comment]
+1

**Comment by JorisPotier** [comment]
:+1:

**Comment by CedricGatay** [comment]
:+1:

**Comment by fchauveau** [comment]
:+1:
